general.vendor=Elecrow
general.name=CrowPanel Basic 7.0"

apps.launcherAppId=tactility.launcher

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=OCT
hardware.spiRamSpeed=120M

hardware.esptoolFlashFreq=120M
hardware.bluetooth=true


storage.userDataLocation=Internal

display.size=7.0"
display.shape=rectangle
display.dpi=187

lvgl.colorDepth=16
lvgl.fontSize=18
sdkconfig.CONFIG_CODEC_DUMMY_SUPPORT=y
